import asyncio
import os
import json
import requests
from mcp_client import MCPClientHelper
from dependency_utils import (
    get_latest_maven_version, 
    get_latest_npm_version, 
    update_pom_xml, 
    update_package_json
)

ROOT_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
GITHUB_REPO = "alvesdesouzaalex/mcp-update-dependency-labs"

async def run_workflow():
    print(f"Starting workflow in {ROOT_DIR}")
    
    # 1. CLEANUP
    print("Step 1: Cleanup node_modules...")
    node_modules = os.path.join(ROOT_DIR, "mcp-frontend", "node_modules")
    if os.path.exists(node_modules):
        # We could use the filesystem MCP to delete, but for speed we use shutil locally
        import shutil
        shutil.rmtree(node_modules)
        print("node_modules removed.")
    else:
        print("node_modules not found, skipping cleanup.")

    # 2. CONNECT TO MCP SERVERS
    print("Step 2: Connecting to MCP Servers...")
    # Using npx to run official servers
    fs_params = ["-y", "@modelcontextprotocol/server-filesystem", ROOT_DIR]
    git_params = ["-y", "@modelcontextprotocol/server-git", "--repository", ROOT_DIR]

    async with MCPClientHelper("npx", fs_params) as fs_client, \
               MCPClientHelper("npx", git_params) as git_client:
        
        print("Connected to MCP servers.")

        # 3. READ DEPENDENCIES
        print("Step 3: Reading dependencies...")
        
        # Backend (Maven)
        pom_path = os.path.join(ROOT_DIR, "mcp-backend", "pom.xml")
        pom_resp = await fs_client.call_tool("read_file", {"path": pom_path})
        pom_content = pom_resp.content[0].text
        
        # Frontend (NPM)
        pkg_path = os.path.join(ROOT_DIR, "mcp-frontend", "package.json")
        pkg_resp = await fs_client.call_tool("read_file", {"path": pkg_path})
        pkg_content = pkg_resp.content[0].text

        # 4. FIND UPDATES
        print("Step 4: Finding updates...")
        
        # Backend Updates
        # Hardcoding targets for this lab, but could be dynamic
        maven_updates = {
            ("org.apache.commons", "commons-lang3"): get_latest_maven_version("org.apache.commons", "commons-lang3")
        }
        
        # Frontend Updates
        npm_updates = {
            "axios": get_latest_npm_version("axios"),
            "lodash": get_latest_npm_version("lodash")
        }

        print(f"Maven Updates: {maven_updates}")
        print(f"NPM Updates: {npm_updates}")

        # 5. APPLY UPDATES
        print("Step 5: Applying updates...")
        new_pom = update_pom_xml(pom_content, maven_updates)
        new_pkg = update_package_json(pkg_content, npm_updates)

        await fs_client.call_tool("write_file", {"path": pom_path, "content": new_pom})
        await fs_client.call_tool("write_file", {"path": pkg_path, "content": new_pkg})

        # 6. GIT WORKFLOW
        print("Step 6: Git Workflow...")
        branch_name = f"update-deps-{os.urandom(2).hex()}"
        
        await git_client.call_tool("git_checkout", {"branch": branch_name, "create_branch": True})
        await git_client.call_tool("git_add", {"files": ["mcp-backend/pom.xml", "mcp-frontend/package.json"]})
        await git_client.call_tool("git_commit", {"message": "chore: update dependencies via MCP workflow"})
        
        # Push requires remote setup, assuming origin exists
        try:
            await git_client.call_tool("git_push", {"remote": "origin", "branch": branch_name})
        except Exception as e:
            print(f"Push failed (expected if remote not configured): {e}")

        # 7. CREATE PULL REQUEST
        print("Step 7: Creating Pull Request...")
        create_pull_request(branch_name)

def create_pull_request(branch_name: str):
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        print("GITHUB_TOKEN not found. Skipping PR creation.")
        return

    url = f"https://api.github.com/repos/{GITHUB_REPO}/pulls"
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    payload = {
        "title": "chore: update dependencies",
        "body": "Automated dependency update generated by mcp-workflow.",
        "head": branch_name,
        "base": "main"
    }
    
    resp = requests.post(url, headers=headers, json=payload)
    if resp.status_code == 201:
        print(f"PR Created successfully: {resp.json().get('html_url')}")
    else:
        print(f"Failed to create PR: {resp.status_code} - {resp.text}")

if __name__ == "__main__":
    asyncio.run(run_workflow())
